spring:
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
  profiles:
    active: "docker,default"
  config:
     import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:9999}

  application:
    name: genre-ms
  datasource:
    url: 'jdbc:h2:mem:gendb'
#
#    url: jdbc:mysql://mysqldb:3306/test?useSSL=false&serverTimezone=UTC
#    username: root
#    password: root

  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  cloud:
    config:
      enabled: true
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true


management:
  endpoints:
    web:
      exposure:
        include: '*'


eureka:  # Move this to root level, not under spring
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    #hostname: theme-ms
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
build:
  version: 1.0
#author:
  #name: "farah guelbi"
#  email: "farah33guelbi@gmail.com"