server:
  port: 8888

spring:
  application:
    name: gatewayserver
  cloud:
    config:
      enabled: false   # Désactive le Config Server
    discovery:
      enabled: true
    gateway:
      routes:
        - id: genre_route
          uri: lb://GENRE-MED-SERVICE
          predicates:
            - Path=/GENRE-MED-SERVICE/**
          filters:
            - StripPrefix=1
        - id: patient_route
          uri: lb://PATIENT
          predicates:
            - Path=/PATIENT/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

  config:
    import-check:
      enabled: false   # Ignore l'absence de config server

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka/'
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      access: unrestricted
